"""outbound_messages outbox

Revision ID: 2dd7fe43c5ec
Revises: de8943be3e33
Create Date: 2026-07-15 17:10:21.817933
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2dd7fe43c5ec'
down_revision: Union[str, None] = 'de8943be3e33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbound_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.String(length=8), nullable=False),
    sa.Column('channel_user_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('attachment_url', sa.String(length=1024), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outbound_messages')
    # ### end Alembic commands ###
