"""integration_settings

Revision ID: 4150145b3532
Revises: 2dd7fe43c5ec
Create Date: 2026-07-15 17:35:31.478436
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4150145b3532'
down_revision: Union[str, None] = '2dd7fe43c5ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('integration_settings')
    # ### end Alembic commands ###
