"""reviews client_id nullable

Revision ID: de8943be3e33
Revises: a0c5de47b246
Create Date: 2026-07-15 02:41:02.525615
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'de8943be3e33'
down_revision: Union[str, None] = 'a0c5de47b246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'client_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'client_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
